/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/block-time/': RouteRecordInfo<
      '/block-time/',
      '/block-time',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/block-time/[id]': RouteRecordInfo<
      '/block-time/[id]',
      '/block-time/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/block-time/new': RouteRecordInfo<
      '/block-time/new',
      '/block-time/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/challenges/': RouteRecordInfo<
      '/challenges/',
      '/challenges',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/challenges/new': RouteRecordInfo<
      '/challenges/new',
      '/challenges/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/day/[date]': RouteRecordInfo<
      '/day/[date]',
      '/day/:date',
      { date: ParamValue<true> },
      { date: ParamValue<false> },
      | never
    >,
    '/habits/': RouteRecordInfo<
      '/habits/',
      '/habits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/habits/[id]/': RouteRecordInfo<
      '/habits/[id]/',
      '/habits/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/habits/[id]/edit': RouteRecordInfo<
      '/habits/[id]/edit',
      '/habits/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/habits/ideas': RouteRecordInfo<
      '/habits/ideas',
      '/habits/ideas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/habits/new': RouteRecordInfo<
      '/habits/new',
      '/habits/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plan': RouteRecordInfo<
      '/plan',
      '/plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/routines/': RouteRecordInfo<
      '/routines/',
      '/routines',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/routines/[id]': RouteRecordInfo<
      '/routines/[id]',
      '/routines/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/routines/build/[id]': RouteRecordInfo<
      '/routines/build/[id]',
      '/routines/build/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/routines/new': RouteRecordInfo<
      '/routines/new',
      '/routines/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/routines/presets': RouteRecordInfo<
      '/routines/presets',
      '/routines/presets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/start': RouteRecordInfo<
      '/start',
      '/start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats': RouteRecordInfo<
      '/stats',
      '/stats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/block-time/index.vue': {
      routes:
        | '/block-time/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/block-time/[id].vue': {
      routes:
        | '/block-time/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/block-time/new.vue': {
      routes:
        | '/block-time/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/challenges/index.vue': {
      routes:
        | '/challenges/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/challenges/new.vue': {
      routes:
        | '/challenges/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/day/[date].vue': {
      routes:
        | '/day/[date]'
      views:
        | never
      pathParamNames:
        | 'date'
    }
    'src/pages/habits/index.vue': {
      routes:
        | '/habits/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/habits/[id]/index.vue': {
      routes:
        | '/habits/[id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/habits/[id]/edit.vue': {
      routes:
        | '/habits/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/habits/ideas.vue': {
      routes:
        | '/habits/ideas'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/habits/new.vue': {
      routes:
        | '/habits/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/plan.vue': {
      routes:
        | '/plan'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/routines/index.vue': {
      routes:
        | '/routines/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/routines/[id].vue': {
      routes:
        | '/routines/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/routines/build/[id].vue': {
      routes:
        | '/routines/build/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/routines/new.vue': {
      routes:
        | '/routines/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/routines/presets.vue': {
      routes:
        | '/routines/presets'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/start.vue': {
      routes:
        | '/start'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/stats.vue': {
      routes:
        | '/stats'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
